patrol_node:
  ros__parameters:
    loop: true
    dwell_time: 5.0
    waypoint_names: ["point_A", "point_B", "point_C"]
    waypoint_x:    [0.696,1.13,1.21]
    waypoint_y:    [-0.299,1.6,-3.4]
    waypoint_yaw:  [0.00201,0.00368,0.00218]